[2024-08-20 10:48:45 +0800] [257778] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['127.0.0.1:8000']
  backlog: 2048
  workers: 3
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/scs22/iGEM-2024-Coders/USTC-Software
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1', '::1']
  accesslog: access.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: error.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: USTC-Software.wsgi:application
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f1fc333cd60>
  on_reload: <function OnReload.on_reload at 0x7f1fc333cea0>
  when_ready: <function WhenReady.when_ready at 0x7f1fc333cfe0>
  pre_fork: <function Prefork.pre_fork at 0x7f1fc333d120>
  post_fork: <function Postfork.post_fork at 0x7f1fc333d260>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f1fc333d3a0>
  worker_int: <function WorkerInt.worker_int at 0x7f1fc333d4e0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f1fc333d620>
  pre_exec: <function PreExec.pre_exec at 0x7f1fc333d760>
  pre_request: <function PreRequest.pre_request at 0x7f1fc333d8a0>
  post_request: <function PostRequest.post_request at 0x7f1fc333d940>
  child_exit: <function ChildExit.child_exit at 0x7f1fc333da80>
  worker_exit: <function WorkerExit.worker_exit at 0x7f1fc333dbc0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f1fc333dd00>
  on_exit: <function OnExit.on_exit at 0x7f1fc333de40>
  ssl_context: <function NewSSLContext.ssl_context at 0x7f1fc333e020>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1', '::1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  permit_obsolete_folding: False
  strip_header_spaces: False
  permit_unconventional_http_method: False
  permit_unconventional_http_version: False
  casefold_http_method: False
  forwarder_headers: ['SCRIPT_NAME', 'PATH_INFO']
  header_map: drop
[2024-08-20 10:48:45 +0800] [257778] [INFO] Starting gunicorn 23.0.0
[2024-08-20 10:48:45 +0800] [257778] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2024-08-20 10:48:45 +0800] [257778] [ERROR] connection to ('127.0.0.1', 8000) failed: [Errno 98] Address already in use
[2024-08-20 10:48:45 +0800] [257778] [DEBUG] Retrying in 1 second.
[2024-08-20 10:48:46 +0800] [257778] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2024-08-20 10:48:46 +0800] [257778] [ERROR] connection to ('127.0.0.1', 8000) failed: [Errno 98] Address already in use
[2024-08-20 10:48:46 +0800] [257778] [DEBUG] Retrying in 1 second.
[2024-08-20 10:48:47 +0800] [257778] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2024-08-20 10:48:47 +0800] [257778] [ERROR] connection to ('127.0.0.1', 8000) failed: [Errno 98] Address already in use
[2024-08-20 10:48:47 +0800] [257778] [DEBUG] Retrying in 1 second.
[2024-08-20 10:48:48 +0800] [257778] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2024-08-20 10:48:48 +0800] [257778] [ERROR] connection to ('127.0.0.1', 8000) failed: [Errno 98] Address already in use
[2024-08-20 10:48:48 +0800] [257778] [DEBUG] Retrying in 1 second.
[2024-08-20 10:48:49 +0800] [257778] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2024-08-20 10:48:49 +0800] [257778] [ERROR] connection to ('127.0.0.1', 8000) failed: [Errno 98] Address already in use
[2024-08-20 10:48:49 +0800] [257778] [DEBUG] Retrying in 1 second.
[2024-08-20 10:48:50 +0800] [257778] [ERROR] Can't connect to ('127.0.0.1', 8000)
[2024-08-20 10:48:57 +0800] [257779] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['127.0.0.1:8000']
  backlog: 2048
  workers: 3
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/scs22/iGEM-2024-Coders/USTC-Software
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1', '::1']
  accesslog: access.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: error.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: USTC-Software.wsgi:application
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7fb4c0374d60>
  on_reload: <function OnReload.on_reload at 0x7fb4c0374ea0>
  when_ready: <function WhenReady.when_ready at 0x7fb4c0374fe0>
  pre_fork: <function Prefork.pre_fork at 0x7fb4c0375120>
  post_fork: <function Postfork.post_fork at 0x7fb4c0375260>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7fb4c03753a0>
  worker_int: <function WorkerInt.worker_int at 0x7fb4c03754e0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7fb4c0375620>
  pre_exec: <function PreExec.pre_exec at 0x7fb4c0375760>
  pre_request: <function PreRequest.pre_request at 0x7fb4c03758a0>
  post_request: <function PostRequest.post_request at 0x7fb4c0375940>
  child_exit: <function ChildExit.child_exit at 0x7fb4c0375a80>
  worker_exit: <function WorkerExit.worker_exit at 0x7fb4c0375bc0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7fb4c0375d00>
  on_exit: <function OnExit.on_exit at 0x7fb4c0375e40>
  ssl_context: <function NewSSLContext.ssl_context at 0x7fb4c0376020>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1', '::1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  permit_obsolete_folding: False
  strip_header_spaces: False
  permit_unconventional_http_method: False
  permit_unconventional_http_version: False
  casefold_http_method: False
  forwarder_headers: ['SCRIPT_NAME', 'PATH_INFO']
  header_map: drop
[2024-08-20 10:48:57 +0800] [257779] [INFO] Starting gunicorn 23.0.0
[2024-08-20 10:48:57 +0800] [257779] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2024-08-20 10:48:57 +0800] [257779] [ERROR] connection to ('127.0.0.1', 8000) failed: [Errno 98] Address already in use
[2024-08-20 10:48:57 +0800] [257779] [DEBUG] Retrying in 1 second.
[2024-08-20 10:48:58 +0800] [257779] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2024-08-20 10:48:58 +0800] [257779] [ERROR] connection to ('127.0.0.1', 8000) failed: [Errno 98] Address already in use
[2024-08-20 10:48:58 +0800] [257779] [DEBUG] Retrying in 1 second.
[2024-08-20 10:48:59 +0800] [257779] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2024-08-20 10:48:59 +0800] [257779] [ERROR] connection to ('127.0.0.1', 8000) failed: [Errno 98] Address already in use
[2024-08-20 10:48:59 +0800] [257779] [DEBUG] Retrying in 1 second.
[2024-08-20 10:49:00 +0800] [257779] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2024-08-20 10:49:00 +0800] [257779] [ERROR] connection to ('127.0.0.1', 8000) failed: [Errno 98] Address already in use
[2024-08-20 10:49:00 +0800] [257779] [DEBUG] Retrying in 1 second.
[2024-08-20 10:49:01 +0800] [257779] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2024-08-20 10:49:01 +0800] [257779] [ERROR] connection to ('127.0.0.1', 8000) failed: [Errno 98] Address already in use
[2024-08-20 10:49:01 +0800] [257779] [DEBUG] Retrying in 1 second.
[2024-08-20 10:49:02 +0800] [257779] [ERROR] Can't connect to ('127.0.0.1', 8000)
